version: 2

sphinx:
  configuration: docs/conf.py

python:
   install:
     # Without this, sphinx can't find pluggy's version.
     - method: pip
       path: .
     - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
