sudo: false
language: python

jobs:
  include:
    - python: '3.6'
      env: TOXENV=linting
    - python: '3.6'
      env: TOXENV=docs
    - python: '2.7'
      env: TOXENV=py27-pytestrelease
    - python: '3.4'
      env: TOXENV=py34-pytestrelease
    - python: '3.5'
      env: TOXENV=py35-pytestrelease
    - python: '3.6'
      env: TOXENV=py36-pytestrelease
    - python: 'pypy'
      env: TOXENV=pypy-pytestrelease
    - python: 'nightly'
      env: TOXENV=py37-pytestrelease
    - python: '2.7'
      env: TOXENV=py27-pytestmaster
    - python: '2.7'
      env: TOXENV=py27-pytestfeatures
    - python: '3.6'
      env: TOXENV=py36-pytestmaster
    - python: '3.6'
      env: TOXENV=py36-pytestfeatures
    - python: '3.6'
      env: TOXENV=benchmark

    - stage: deploy
      python: '3.6'
      env:
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: PDvQCKfXrF1V/tdwEOfeDEjDs6vJ9gKWo4yrMUmBx1JL5plHZaqfHLftlGMoHekaQTHcfyYYbxignFw5IGsn97/nFKKWDPNBfZA+3RJJmeJfz2NQunYkSnoqtBtfEtWHzFPdkCm0w/CN9C8IpRjhvLnFTUQzil6iMy6wZG276gU=
        on:
          tags: true
          repo: pytest-dev/pluggy

install:
  - pip install -U setuptools pip
  - pip install -U tox

script:
  - tox

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
