[git]
url = "https://github.com/devpi/devpi"
into = "devpi"

[environment]
kind = "uv-venv"

[environment.install]
editables = ["common", "server", "client", "web", "../.."]

[environment.install.uv]
groups = ["pytest"]

[[test]]
argv = ["pytest", "common"]

[[test]]
argv = ["pytest", "server"]

[[test]]
argv = ["pytest", "client"]

[[test]]
argv = ["pytest", "web"]
