[git]
url = "https://github.com/pypa/hatch"
into = "hatch"

[environment]
kind = "uv-venv"

[environment.install]
editables = [".", "./backend", "../.."]

[environment.install.uv]
packages = [
    "pytest",
    "pytest-mock",
    "pytest-xdist",
    "filelock",
    "flit-core",
    "trustme",
    "editables",
]

[[test]]
argv = ["pytest", "tests/backend"]
